services:
  mysql:
    image: mysql:8
    container_name: mysqll
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin 
      MYSQL_DATABASE: testdb
    volumes:
      - vol:/var/lib/mysql
    networks:
      - mynet  

  web:
    build: .
    container_name: webapppp
    ports:
      - "3006:3000"
    depends_on:
      - mysql
    networks:
      - mynet    

volumes:
  vol:

networks:
  mynet: